package organitzacions;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/organitzacio") // This means URL's start with /demo (after Application path)
public class OrganitzacioController {
	
	@Autowired
	private OrganitzacioRepository organitzacioRepository;
	
	@GetMapping(path="/allOrganitzacions")
	public @ResponseBody Iterable<Organitzacio> getAllOrganitzacions() {
		return organitzacioRepository.findAll();
	}
	
	/*@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	
	@GetMapping(path="/addServei") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}
	
	@GetMapping(path="/allServeis")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
<<<<<<< HEAD:src/main/java/hello/MainController.java
	}
	
	@GetMapping(path="/addOficina")
	public @ResponseBody String addNewOficina(@RequestParam Integer id, @RequestParam Integer Codi, @RequestParam String Poblacio, @RequestParam String provincia, @RequestParam String Direccio){
		
	}
=======
	}*/
>>>>>>> 9fc6bbff759e19b4f7b8825805c0461fdf2b17db:src/main/java/organitzacions/OrganitzacioController.java
}
